--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DRAGONPMMP/HealthDefenceMana-DISPLAY
build-by-default: true
branches:
- main
projects:
  HealthDefenceMana-DISPLAY:
    path: ""
...
